CarService/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarService.Models;
using System.Xml.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;


namespace CarService.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {

            var customers = db.Customers.Include(c => c.frequency);
            return View(customers.ToList());
        }

        public ActionResult Search123()
        {
            var customers = db.Customers.Include(c => c.frequency);
            return View(customers.ToList());
        }

        // GET: Customers/Details/5
        public static int newid;
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            newid = id.GetValueOrDefault();
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            ViewBag.FrequencyID = new SelectList(db.Frequencies, "id", "description");
            return View();
        }

        //public static void getLatLng(Customer customer)
        //{
        //    string add = customer.street1 + "," + customer.street2 + "," + customer.city + "," + customer.state;
        //    var address = add;
        //    var requestUri = string.Format("http://maps.googleapis.com/maps/api/geocode/xml?address={0}&sensor=false", Uri.EscapeDataString(address));

        //    var request = WebRequest.Create(requestUri);
        //    var response = request.GetResponse();
        //    var xdoc = XDocument.Load(response.GetResponseStream());

        //    var result = xdoc.Element("GeocodeResponse").Element("result");
        //    var locationElement = result.Element("geometry").Element("location");
        //    var lat = locationElement.Element("lat");
        //    var lng = locationElement.Element("lng");
        //    customer.latitude = (double)lat;
        //    customer.longitude = (double)lng;
        //}


        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,phoneNumber,CarModel,CarMake,CarCapacity,CarAverage,PerHourRate,Available,FrequencyID,street1,stree2,city,state")] Customer customer, DateTime FreeFrom, DateTime FreeTo)
        {
            if(ModelState.IsValid)
            {
                DateTime d = FreeFrom;
                TimeSpan timeOfDay = d.TimeOfDay;
                string freef = timeOfDay.Hours.ToString();
                DateTime d1 = FreeTo;
                TimeSpan timeOfDay1 = d1.TimeOfDay;
                string freet = timeOfDay1.Hours.ToString();
                string add = customer.street1 + "," + customer.street2 + "," + customer.city + "," + customer.state;
                var address = add;
                var requestUri = string.Format("http://maps.googleapis.com/maps/api/geocode/xml?address={0}&sensor=false", Uri.EscapeDataString(address));

                var request = WebRequest.Create(requestUri);
                var response = request.GetResponse();
                var xdoc = XDocument.Load(response.GetResponseStream());

                var result = xdoc.Element("GeocodeResponse").Element("result");
                var locationElement = result.Element("geometry").Element("location");
                var lat = locationElement.Element("lat");
                var lng = locationElement.Element("lng");
                customer.latitude = (double)lat;
                customer.longitude = (double)lng;

                int num11, num22;
                bool num1 = int.TryParse(freef, out num11);
                bool num2 = int.TryParse(freet, out num22);
                customer.FreeFrom = num11;
                customer.FreeTo = num22;
                customer.email = User.Identity.Name;
                //getLatLng(customer);
            }
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FrequencyID = new SelectList(db.Frequencies, "id", "description", customer.FrequencyID);
            return View(customer);
        }


        public ActionResult Search()
        {
            List<Customer> cust1 = new List<Customer>();

            cust1 = db.Customers.Where(c => c.Available==true).ToList();
            return View(cust1);
        }

        [HttpPost]
        public ActionResult Search(DateTime? freefrom, DateTime? freeto)
        {
            // flag if search has been performed
            List<Customer> cust1 = new List<Customer>();
            List<Customer> cust2 = new List<Customer>();
            cust1 = db.Customers.Where(c => c.Available == true).ToList();
            Boolean searchPerformed = false;


            if (freefrom.ToString() == null && freeto.ToString() == null)
            {
                return View(cust1);
            }
            DateTime d = freefrom.GetValueOrDefault();
            TimeSpan timeOfDay = d.TimeOfDay;
            string freef = timeOfDay.Hours.ToString();

            DateTime d1 = freeto.GetValueOrDefault();
            TimeSpan timeOfDay1 = d1.TimeOfDay;
            string freet = timeOfDay1.Hours.ToString();
            //string freef = d.ToShortTimeString();

            //for (int i= freef.Length; i> 0; i -- )
            //{
            //    if(freef[i-1].Equals("P")) 
            //}
            int num11, num22;
            bool num1 = int.TryParse(freef, out num11);
            bool num2 = int.TryParse(freet, out num22);
            cust2 = db.Customers.Where(c => c.FreeFrom >= num11 && c.FreeTo <= num22 && c.Available == true).ToList();
            if (cust2.Count != 0)
            {
                searchPerformed = true;
            }
            //if (!(String.IsNullOrWhiteSpace(freeto) && String.IsNullOrWhiteSpace(freefrom)))
            //{
            //    searchPerformed = true;
            //}


            //    //var cust = db.Customers;
            //    int searchfreefrom;
            //    int searchfreeto;
            //    bool num1;
            //    bool num2;
            //    num1 = int.TryParse(freefrom, out searchfreefrom);
            //    num2 = int.TryParse(freeto, out searchfreeto);



            //foreach (var c in cust1)
            //{

            //    int freefrominteger;
            //    int freetointeger;
            //    bool test;
            //    bool test2;
            //    test = int.TryParse(c.FreeFrom, out freefrominteger);
            //    test2 = int.TryParse(c.FreeTo, out freetointeger);
            //    if (freefrominteger >= searchfreefrom && freetointeger <= searchfreeto && c.Available==true)
            //    {
            //        cust2.Add(c);
            //    }

            //}

            //ViewBag.customerlist = cust2;

            // filter first names if firstName search value provided
            //if (!string.IsNullOrWhiteSpace(firstName))
            //{
            //    contacts = contacts.Where(x => x.FirstName.Contains(firstName));
            //    searchPerformed = true;
            //}

            //// filter last names if lastName search value provided
            //if (!string.IsNullOrWhiteSpace(lastName))
            //{
            //    contacts = contacts.Where(x => x.LastName.Contains(lastName));
            //    searchPerformed = true;
            //}

            //// filter phone numbers if phone search value provided
            //if (!string.IsNullOrWhiteSpace(phone))
            //{
            //    contacts = contacts.Where(x => x.PhoneNumber.Contains(phone));
            //    searchPerformed = true;
            //}


            if (searchPerformed)
            {
                // return search results
                //return View(cust.ToList());
                return View(cust2);
            }
            else
            {
                // return empty list
                return View(cust2);
            }

        }


        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.FrequencyID = new SelectList(db.Frequencies, "id", "description", customer.FrequencyID);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,phoneNumber,CarModel,CarMake,CarCapacity,CarAverage,PerHourRate,FreeFrom,FreeTo,Available,FrequencyID,street1,street2,city,state")] Customer customer)
        {
            bool custsameasuser = db.Customers.Any(x => x.id == customer.id && x.email == User.Identity.Name);
            if(custsameasuser==false)
            {

CarService/Controllers/FrequenciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarService.Models;

namespace CarService.Controllers
{
    [Authorize (Roles ="Admin")]
    public class FrequenciesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Frequencies
        public ActionResult Index()
        {
            return View(db.Frequencies.ToList());
        }

        // GET: Frequencies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frequency frequency = db.Frequencies.Find(id);
            if (frequency == null)
            {
                return HttpNotFound();
            }
            return View(frequency);
        }

        // GET: Frequencies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Frequencies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,description")] Frequency frequency)
        {
            if (ModelState.IsValid)
            {
                db.Frequencies.Add(frequency);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(frequency);
        }

        // GET: Frequencies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frequency frequency = db.Frequencies.Find(id);
            if (frequency == null)
            {
                return HttpNotFound();
            }
            return View(frequency);
        }

        // POST: Frequencies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,description")] Frequency frequency)
        {
            if (ModelState.IsValid)
            {
                db.Entry(frequency).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(frequency);
        }

        // GET: Frequencies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frequency frequency = db.Frequencies.Find(id);
            if (frequency == null)
            {
                return HttpNotFound();
            }
            return View(frequency);
        }

        // POST: Frequencies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Frequency frequency = db.Frequencies.Find(id);
            db.Frequencies.Remove(frequency);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>KAM Car Rental</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    @Styles.Render("~/Content/css/material-kit.css", "~/Content/css/demo.css")


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body class="index-page">
    <!-- Navbar -->
    <nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("KAM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="collapse navbar-collapse" id="navigation-index">
            <ul class="nav navbar-nav navbar-right">

            @if (Request.IsAuthenticated)
            {
                <li>
                    @Html.ActionLink("Customer", "Index", "Customers")
                </li>

                if (User.IsInRole("Admin"))
                {
                <li>
                    @Html.ActionLink("Frequency", "Index", "Frequencies")
                </li>
                }
                <li>
                    @Html.ActionLink("Search Car", "Search", "Customers")
                </li>
            }
                @Html.Partial("_LoginPartial")
                <li>
                    &nbsp;
                </li>
            </ul>
        </div>

    </nav>
    <!-- End Navbar -->

    <div class="body-content">
        <div class="wrapper">
            <div class="header header-filter" style="background-image: url('http://www.araspot.com/wp-content/uploads/2015/06/autumn-cars-best-wallpaper-picture-uwz1vo.jpg');">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="brand">
                                <h1>KAM Car-Rental</h1>
                                <h3>An Airbnb for cars!</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="main main-raised container">

                    @RenderBody()
                    </div>
                </div>
                </div>

                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @Scripts.Render("~/Content/js/material.min.js", "~/Content/js/nouislider.min.js", "~/Content/js/bootstrap-datepicker.js", "~/Content/js/material-kit.js")
                @RenderSection("scripts", required: false)
</body>
<script type="text/javascript">

		$().ready(function(){
			// the body of this function is in assets/material-kit.js
			materialKit.initSliders();
            window_width = $(window).width();

            if (window_width >= 992){
                big_image = $('.wrapper > .header');

				$(window).on('scroll', materialKitDemo.checkScrollForParallax);
			}

		});
</script>
</html>